server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: use-service
          uri: http://localhost:8090
          predicates:
            - Path=/use-service/**
          filters:
            - StripPrefix=1

auth:
  whitelist:
    - /use-service/auth
    - /api/public
    - /health
    - /swagger-ui
    - /v3/api-docs
